pipeline:

  lint:
    image: registry.cn-shenzhen.aliyuncs.com/ike_template/ike:v1
    commands:
    - cd src
    - ls -al
    - poetry config virtualenvs.create false
    - poetry install || poetry install || poetry install
    - yapf -dr . | (! grep '.')
    - isort . --check-only --diff
